apiVersion: v1
kind: Pod
metadata:
    name: fortune2s
spec:
    containers:
        - image: luksa/fortune:args
          env:
              - name: INTERVAL
                value: "30"
          name: html-generator
          volumeMounts:
              - name: html
                mountPath: /var/htdocs
