apiVersion: v1
kind: Pod
metadata:
    name: fortune-args-from_configmap
spec:
    containers:
        - image: luksa/fortune:env
          env:
              - name: INTERVAL
                valueFrom:
                    configMapKeyRef:
                        name: fortune-config
                        key: sleep-interval
          args: ["$(INTERVAL)"]
